apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yml: |
    tunnel: 7acb31a9-acc9-4f56-b46c-a27225f878cb
    credentials-file: /secrets/credentials.json

    ingress:
      - hostname: tunnel-api-{{ .Values.envGroup }}.rtarf-censor.dev-hubs.com
        service: http://pp-{{ .Values.envGroup }}-pp-api:80
      - service: http_status:404
