apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.12.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: cloudflared-config
          projected:
            sources:
              - configMap:
                  name: cloudflared-config
              - secret:
                  name: cloudflared-creds
