{{- if eq .Values.envGroup "dev" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.1.2
          args:
            - tunnel
            - --config
            - /data/config.yaml
            - run
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 512m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /data
            - name: creds
              mountPath: /secrets
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
        - name: creds
          secret:
            secretName: cloudflared-creds
{{- end }}
